name: cd

on:
  workflow_run:
    workflows: ['ci']
    types:
      - completed

jobs:
  start:
    runs-on: movie-hw

    steps:
      - name: stop container
        run: sudo docker container stop con-rap-service-movie
      
      - name: delete container
        run: sudo docker container remove con-rap-service-movie

      - name: delete image
        run: sudo docker image remove phonghuynh1501/img-rap-service

      - name: rerun source
        run: sudo docker compose up -d